let model={events:[],sessions:[],alerts:[],clients:[]};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options){const r=await fetch(path,options),x=await r.json();if(!r.ok)throw new Error(x.error||'Request failed');return x}
async function init(){try{const s=await api('/api/status');if(!s.configured){$('#setup').classList.remove('hidden');$('#status').textContent='Setup required'}else{showDashboard();await Promise.all([load(),loadSettings()])}}catch(e){$('#status').textContent='Offline'}}
function showDashboard(){$('#setup').classList.add('hidden');$('#dashboard').classList.remove('hidden')}
$('#setupForm').addEventListener('submit',async e=>{e.preventDefault();$('#setupError').textContent='';try{await api('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseUrl:$('#baseUrl').value,username:$('#username').value,password:$('#password').value})});showDashboard();await load()}catch(x){$('#setupError').textContent=x.message}});
async function load(){$('#status').textContent='Refreshing…';try{model=await api('/api/dashboard?hours='+$('#hours').value);render();$('#status').textContent='Updated '+new Date(model.generatedAt).toLocaleTimeString()}catch(e){$('#status').textContent='Connection error';alert(e.message)}}
function deviceEvents(){const c=$('#client').value;return model.events.filter(x=>!c||x.client===c)}
function visibleEvents(events){const mode=$('#activity').value,q=$('#domainSearch').value.trim().toLowerCase(),showIgnored=$('#showIgnored').checked;return events.filter(e=>{if(e.ignored&&!showIgnored)return false;if(q&&!e.domain.includes(q))return false;if(mode==='all')return true;if(mode==='adult')return e.category==='adult';if(mode==='bypass')return e.category==='bypass';if(mode==='blocked')return e.status==='blocked';return e.category!=='other'})}
function filtered(){const c=$('#client').value,events=deviceEvents();return{events:visibleEvents(events),allEvents:events,sessions:model.sessions.filter(x=>!c||x.client===c)}}
function csvDownload(name,rows){const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function render(){
 const prior=$('#client').value;$('#client').innerHTML='<option value="">All devices</option>'+model.clients.map(c=>`<option value="${esc(c.client)}">${esc(c.clientName)}</option>`).join('');$('#client').value=prior;
 const x=filtered(),all=x.allEvents;
 $('#sessionCount').textContent=x.sessions.length;$('#directCount').textContent=all.filter(e=>e.evidence==='direct').length;$('#streamCount').textContent=all.filter(e=>e.evidence==='stream').length;$('#bypassCount').textContent=all.filter(e=>e.category==='bypass').length;
 $('#deviceCount').textContent=new Set(all.map(e=>e.client)).size;$('#domainCount').textContent=new Set(all.map(e=>e.domain)).size;$('#blockedCount').textContent=all.filter(e=>e.status==='blocked').length;$('#requestCount').textContent=all.length;
 $('#sessions').innerHTML=x.sessions.length?x.sessions.map(s=>`<div class="session"><div><strong>${esc(s.clientName)}</strong><div class="when">${esc(s.client)}</div></div><div><strong>${new Date(s.start).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}–${new Date(s.end).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</strong><div class="when">${new Date(s.start).toLocaleDateString()} · ~${s.durationMinutes} min</div></div><div><strong>${esc(s.assessment)}</strong><div class="domains">${s.domains.map(esc).join(', ')}</div></div><div><strong>${s.confidence}%</strong><div class="confidence"><i style="width:${s.confidence}%"></i></div></div></div>`).join(''):'<p>No adult activity detected during this period.</p>';
 const mode=$('#activity').value;$('#timelineTitle').textContent=mode==='all'?'All network activity':'Evidence timeline';$('#timelineHelp').textContent=mode==='all'?'Every DNS domain recorded by AdGuard Home for the selected device and period. A lookup does not prove a page was viewed.':'Filtered evidence signals. Combine direct-site and delivery requests before drawing conclusions.';
 $('#events').innerHTML=x.events.slice(0,1000).map(e=>`<tr class="${e.ignored?'ignoredRow':''}"><td>${new Date(e.time).toLocaleString()}</td><td>${esc(e.clientName)}</td><td><strong>${esc(e.domain)}</strong><span class="domainDescription">${esc(e.description)}</span></td><td><span class="result ${e.status==='blocked'?'blocked':''}">${esc(e.status)}</span></td><td><span class="pill ${esc(e.evidence)}">${esc(e.label)}</span></td><td>${e.confidence?e.confidence+'%':'—'}</td><td><button class="tiny ignoreEvidence" data-domain="${esc(e.domain)}" data-ignored="${e.ignored?'false':'true'}">${e.ignored?'Restore':'Ignore'}</button></td></tr>`).join('')||'<tr><td colspan="7">No matching requests.</td></tr>';
 $('#resultSummary').textContent=`Showing ${Math.min(x.events.length,1000).toLocaleString()} of ${x.events.length.toLocaleString()} matching requests${x.events.length>1000?' (display limited to 1,000)':''}.`;
 $('#aliases').innerHTML=model.clients.map(c=>`<label class="alias"><span>${esc(c.client)}</span><span class="mac">${esc(c.mac||'MAC not found')}</span><input data-ip="${esc(c.client)}" data-mac="${esc(c.mac||'')}" value="${esc(c.clientName===c.client?'':c.clientName)}" placeholder="Device name"></label>`).join('')
	 $('#alerts').innerHTML=(model.alerts||[]).filter(a=>!$('#client').value||a.client===$('#client').value).map(a=>`<article class="alert ${esc(a.severity)}"><div><strong>${esc(a.title)}</strong><span>${esc(a.clientName)} · ${new Date(a.time).toLocaleString()}</span></div><div>${esc(a.detail)} · ${a.confidence}% confidence</div></article>`).join('')||'<p>No alert-level signals for this selection.</p>';
}
$('#refresh').onclick=load;$('#hours').onchange=load;$('#client').onchange=render;$('#activity').onchange=render;$('#domainSearch').oninput=render;$('#showIgnored').onchange=render;
$('#events').onclick=async e=>{const b=e.target.closest('.ignoreEvidence');if(!b)return;b.disabled=true;const domain=b.dataset.domain.toLowerCase(),ignored=b.dataset.ignored==='true';try{await api('/api/ignored',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain,ignored})});model.events.forEach(x=>{if(x.domain.toLowerCase()===domain)x.ignored=ignored});render()}catch(x){alert(x.message);b.disabled=false}};
$('#saveAliases').onclick=async()=>{const aliases={},macAliases={};document.querySelectorAll('[data-ip]').forEach(i=>{const name=i.value.trim();if(!name)return;if(i.dataset.mac)macAliases[i.dataset.mac.toUpperCase()]=name;else aliases[i.dataset.ip]=name});await api('/api/aliases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({aliases,macAliases})});await load()};
$('#discoverNames').onclick=async()=>{$('#discoverNames').disabled=true;$('#discoveryStatus').textContent='Scanning reverse DNS, NetBIOS, and ARP (usually under one minute)…';try{await api('/api/discover',{method:'POST'});$('#discoveryStatus').textContent='Scan complete. Devices with NetBIOS disabled may show only an IP and MAC address.';await load()}catch(e){$('#discoveryStatus').textContent=e.message}finally{$('#discoverNames').disabled=false}};
$('#exportCsv').onclick=()=>{const x=filtered().sessions;csvDownload('HomeWatch-sessions.csv',[['Device','IP','Start','End','Minutes','Assessment','Confidence','Domains'],...x.map(s=>[s.clientName,s.client,s.start,s.end,s.durationMinutes,s.assessment,s.confidence,s.domains.join(' | ')])])};
$('#exportActivity').onclick=()=>{const x=filtered().events;csvDownload('HomeWatch-activity.csv',[['Time','Device','IP','Domain','Description','Result','Evidence','Confidence'],...x.map(e=>[e.time,e.clientName,e.client,e.domain,e.description,e.status,e.label,e.confidence])])};
$('#exportJson').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(filtered().events,null,2)],{type:'application/json'}));a.download='HomeWatch-activity.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
async function loadSettings(){const s=await api('/api/settings');$('#retentionDays').value=s.retentionDays;$('#categoryListUrl').value=s.categoryListUrl||'';$('#autoUpdateCategories').checked=!!s.autoUpdateCategories;$('#adguardLink').href=s.adGuardUrl||'http://127.0.0.1'}
async function saveSettings(updateNow){$('#settingsStatus').textContent='Saving…';try{await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({retentionDays:Number($('#retentionDays').value),categoryListUrl:$('#categoryListUrl').value.trim(),autoUpdateCategories:$('#autoUpdateCategories').checked,updateNow})});$('#settingsStatus').textContent=updateNow?'Settings saved and category list updated.':'Settings saved.'}catch(e){$('#settingsStatus').textContent=e.message}}
$('#settingsForm').onsubmit=e=>{e.preventDefault();saveSettings(false)};$('#updateCategories').onclick=()=>saveSettings(true);init();
