let model={events:[],sessions:[],clients:[]};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options){const r=await fetch(path,options);const x=await r.json();if(!r.ok)throw new Error(x.error||'Request failed');return x}
async function init(){try{const s=await api('/api/status');if(!s.configured){$('#setup').classList.remove('hidden');$('#status').textContent='Setup required'}else{showDashboard();await load()}}catch(e){$('#status').textContent='Offline'}}
function showDashboard(){$('#setup').classList.add('hidden');$('#dashboard').classList.remove('hidden')}
$('#setupForm').addEventListener('submit',async e=>{e.preventDefault();$('#setupError').textContent='';try{await api('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseUrl:$('#baseUrl').value,username:$('#username').value,password:$('#password').value})});showDashboard();await load()}catch(x){$('#setupError').textContent=x.message}});
async function load(){ $('#status').textContent='Refreshing…';try{model=await api('/api/dashboard?hours='+$('#hours').value);render();$('#status').textContent='Updated '+new Date(model.generatedAt).toLocaleTimeString()}catch(e){$('#status').textContent='Connection error';alert(e.message)}}
function filtered(){const c=$('#client').value;return{events:model.events.filter(x=>!c||x.client===c),sessions:model.sessions.filter(x=>!c||x.client===c)}}
function render(){const prior=$('#client').value;$('#client').innerHTML='<option value="">All devices</option>'+model.clients.map(c=>`<option value="${esc(c.client)}">${esc(c.clientName)}</option>`).join('');$('#client').value=prior;const x=filtered();$('#sessionCount').textContent=x.sessions.length;$('#directCount').textContent=x.events.filter(e=>e.evidence==='direct').length;$('#streamCount').textContent=x.events.filter(e=>e.evidence==='stream').length;$('#bypassCount').textContent=x.events.filter(e=>e.category==='bypass').length;
$('#sessions').innerHTML=x.sessions.length?x.sessions.map(s=>`<div class="session"><div><strong>${esc(s.clientName)}</strong><div class="when">${esc(s.client)}</div></div><div><strong>${new Date(s.start).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}–${new Date(s.end).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</strong><div class="when">${new Date(s.start).toLocaleDateString()} · ~${s.durationMinutes} min</div></div><div><strong>${esc(s.assessment)}</strong><div class="domains">${s.domains.map(esc).join(', ')}</div></div><div><strong>${s.confidence}%</strong><div class="confidence"><i style="width:${s.confidence}%"></i></div></div></div>`).join(''):'<p>No adult activity detected during this period.</p>';
$('#events').innerHTML=x.events.slice(0,500).map(e=>`<tr><td>${new Date(e.time).toLocaleString()}</td><td>${esc(e.clientName)}</td><td>${esc(e.domain)}</td><td><span class="pill ${esc(e.evidence)}">${esc(e.label)}</span></td><td>${e.confidence}%</td></tr>`).join('');
$('#aliases').innerHTML=model.clients.map(c=>`<label class="alias">${esc(c.client)}<input data-ip="${esc(c.client)}" value="${esc(c.clientName===c.client?'':c.clientName)}" placeholder="Device name"></label>`).join('')}
$('#refresh').onclick=load;$('#hours').onchange=load;$('#client').onchange=render;
$('#saveAliases').onclick=async()=>{const aliases={};document.querySelectorAll('[data-ip]').forEach(i=>{if(i.value.trim())aliases[i.dataset.ip]=i.value.trim()});await api('/api/aliases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({aliases})});await load()};
$('#exportCsv').onclick=()=>{const x=filtered().sessions;const rows=[['Device','IP','Start','End','Minutes','Assessment','Confidence','Domains'],...x.map(s=>[s.clientName,s.client,s.start,s.end,s.durationMinutes,s.assessment,s.confidence,s.domains.join(' | ')])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='HomeWatch-sessions.csv';a.click()};init();
