let model={events:[],sessions:[],alerts:[],alertAuditLog:[],clients:[]},loading=false;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options){const r=await fetch(path,options),x=await r.json();if(!r.ok)throw new Error(x.error||'Request failed');return x}
async function init(){try{const s=await api('/api/status');if(!s.configured){$('#setup').classList.remove('hidden');$('#status').textContent='Setup required'}else{showDashboard();await Promise.all([load(),loadSettings()])}}catch(e){$('#status').textContent='Offline'}}
function showDashboard(){$('#setup').classList.add('hidden');$('#dashboard').classList.remove('hidden')}
$('#setupForm').addEventListener('submit',async e=>{e.preventDefault();$('#setupError').textContent='';try{await api('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseUrl:$('#baseUrl').value,username:$('#username').value,password:$('#password').value})});showDashboard();await load()}catch(x){$('#setupError').textContent=x.message}});
async function load(silent=false){if(loading)return;loading=true;if(!silent)$('#status').textContent='Refreshing…';try{model=await api('/api/dashboard?hours='+$('#hours').value);render();$('#status').textContent='Live · updated '+new Date(model.generatedAt).toLocaleTimeString()+(model.eventReadErrors?' · '+model.eventReadErrors+' unreadable records':'')}catch(e){$('#status').textContent='Connection error';if(!silent)alert(e.message)}finally{loading=false}}
function deviceEvents(){const c=$('#client').value;return model.events.filter(x=>!c||x.client===c)}
function visibleEvents(events){const mode=$('#activity').value,q=$('#domainSearch').value.trim().toLowerCase(),showIgnored=$('#showIgnored').checked;return events.filter(e=>{if(e.ignored&&!showIgnored)return false;if(q&&!e.domain.includes(q))return false;if(mode==='all')return true;if(mode==='adult')return e.category==='adult';if(mode==='bypass')return e.category==='bypass';if(mode==='blocked')return e.status==='blocked';return e.category!=='other'})}
function filtered(){const c=$('#client').value,events=deviceEvents();return{events:visibleEvents(events),allEvents:events,sessions:model.sessions.filter(x=>!c||x.client===c)}}
function csvDownload(name,rows){const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function render(){
 const prior=$('#client').value;$('#client').innerHTML='<option value="">All devices</option>'+model.clients.map(c=>`<option value="${esc(c.client)}">${esc(c.clientName)}</option>`).join('');$('#client').value=prior;
 const x=filtered(),all=x.allEvents;
 $('#sessionCount').textContent=x.sessions.length;$('#directCount').textContent=all.filter(e=>e.evidence==='direct').length;$('#streamCount').textContent=all.filter(e=>e.evidence==='stream').length;$('#bypassCount').textContent=all.filter(e=>e.category==='bypass').length;
 $('#deviceCount').textContent=new Set(all.map(e=>e.client)).size;$('#domainCount').textContent=new Set(all.map(e=>e.domain)).size;$('#blockedCount').textContent=all.filter(e=>e.status==='blocked').length;$('#requestCount').textContent=all.length;
 $('#sessions').innerHTML=x.sessions.length?x.sessions.map(s=>`<div class="session"><div><strong>${esc(s.clientName)}</strong><div class="when">${esc(s.client)}</div></div><div><strong>${new Date(s.start).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}–${new Date(s.end).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</strong><div class="when">${new Date(s.start).toLocaleDateString()} · ${s.durationSeconds}s observed</div></div><div><strong>${esc(s.assessment)}</strong><div class="sessionNarrative">${esc(s.narrative)}</div><div class="sessionFacts">${s.logicalContacts} logical contacts · ${s.possiblePlaybackPhases} possible playback phase${s.possiblePlaybackPhases===1?'':'s'} · ${s.assetLoadingBursts} asset-loading burst${s.assetLoadingBursts===1?'':'s'} · ${s.advertisingRequests||0} advertising requests${s.timeToFirstStreamSeconds!=null?' · media after '+s.timeToFirstStreamSeconds+'s':''}</div><div class="domains">${s.domains.map(esc).join(', ')}</div></div><div><strong>${s.confidence}%</strong><div class="confidence"><i style="width:${s.confidence}%"></i></div></div></div>`).join(''):'<p>No adult activity detected during this period.</p>';
 const mode=$('#activity').value;$('#timelineTitle').textContent=mode==='all'?'All network activity':'Evidence timeline';$('#timelineHelp').textContent=mode==='all'?'Every DNS domain recorded by AdGuard Home for the selected device and period. A lookup does not prove a page was viewed.':'Filtered evidence signals. Combine direct-site and delivery requests before drawing conclusions.';
 $('#events').innerHTML=x.events.slice(0,1000).map(e=>`<tr class="${e.ignored?'ignoredRow':''}"><td>${new Date(e.time).toLocaleString()}</td><td>${esc(e.clientName)}</td><td><strong>${esc(e.domain)}</strong><span class="domainDescription">${esc(e.serviceOwner&&e.serviceOwner!=='Not established'?e.serviceOwner+' · ':'')}${esc(e.serviceCategory||e.description)} · ${esc(e.serviceCategoryConfidence||0)}% category confidence</span><button class="explainDomain" data-domain="${esc(e.domain)}">Explain domain</button><span class="domainIntel"></span></td><td><span class="result ${e.status==='blocked'?'blocked':''}">${esc(e.status)}</span></td><td><span class="pill ${esc(e.evidence)}">${esc(e.label)}</span></td><td>${e.confidence?e.confidence+'%':'—'}</td><td><button class="tiny ignoreEvidence" data-domain="${esc(e.domain)}" data-ignored="${e.ignored?'false':'true'}">${e.ignored?'Restore':'Ignore'}</button></td></tr>`).join('')||'<tr><td colspan="7">No matching requests.</td></tr>';
 $('#resultSummary').textContent=`Showing ${Math.min(x.events.length,1000).toLocaleString()} of ${x.events.length.toLocaleString()} matching requests${x.events.length>1000?' (display limited to 1,000)':''}.`;
 $('#aliases').innerHTML=model.clients.map(c=>`<label class="alias"><span>${esc(c.client)}</span><span class="mac">${esc(c.mac||'MAC not found')}</span><input data-ip="${esc(c.client)}" data-mac="${esc(c.mac||'')}" value="${esc(c.clientName===c.client?'':c.clientName)}" placeholder="Device name"></label>`).join('')
	 $('#alerts').innerHTML=(model.alerts||[]).filter(a=>!$('#client').value||a.client===$('#client').value).map(a=>`<article class="alert ${esc(a.severity)} ${a.acknowledged?'acknowledged':''}"><div><strong>${esc(a.title)}</strong><span>${esc(a.clientName)} · ${new Date(a.time).toLocaleString()}</span></div><div>${esc(a.detail)} · ${a.confidence}% confidence<span>${a.notificationSent?'Phone notification sent '+new Date(a.notificationSentAt).toLocaleString():'Phone notification not sent'} · ${a.acknowledged?'Acknowledged '+new Date(a.acknowledgedAt).toLocaleString():'Not acknowledged'}</span></div><button class="tiny acknowledgeAlert" data-id="${esc(a.id)}" data-acknowledged="${a.acknowledged?'false':'true'}">${a.acknowledged?'Reopen':'Acknowledge'}</button></article>`).join('')||'<p>No alert-level signals for this selection.</p>';
	 $('#alertHistory').innerHTML=(model.alertAuditLog||[]).map(h=>`<tr><td>${new Date(h.at).toLocaleString()}</td><td><span class="auditAction ${esc(h.action)}">${esc(h.action)}</span></td><td>${esc(h.clientName||h.client||'Unknown device')}</td><td>${esc(h.title||'Adult activity session')}<span class="domainDescription">${esc(h.detail||'')}</span></td></tr>`).join('')||'<tr><td colspan="4">No acknowledgement activity yet.</td></tr>';
}
$('#refresh').onclick=load;$('#hours').onchange=load;$('#client').onchange=render;$('#activity').onchange=render;$('#domainSearch').oninput=render;$('#showIgnored').onchange=render;
$('#alerts').onclick=async e=>{const b=e.target.closest('.acknowledgeAlert');if(!b)return;b.disabled=true;const a=(model.alerts||[]).find(x=>x.id===b.dataset.id)||{};try{await api('/api/alerts/acknowledge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:b.dataset.id,acknowledged:b.dataset.acknowledged==='true',client:a.client,clientName:a.clientName,alertTime:a.time,title:a.title,detail:a.detail})});await load()}catch(x){alert(x.message);b.disabled=false}};
$('#events').onclick=async e=>{const explain=e.target.closest('.explainDomain');if(explain){explain.disabled=true;const out=explain.parentElement.querySelector('.domainIntel');out.textContent='Looking up domain intelligence…';try{const x=await api('/api/domain-info?domain='+encodeURIComponent(explain.dataset.domain)),cats=(x.categories||[]).join(', '),a=x.analysis||{};out.innerHTML=`<strong>Owner:</strong> ${esc(x.owner||'Not established')}<br><strong>Category:</strong> ${esc(x.localCategory||'Application or web service')} · ${esc(x.categoryConfidence||0)}% confidence<br><strong>Category source:</strong> ${esc(x.categoryBasis||'General classification')}${x.parentDomain&&x.parentDomain!==x.domain?` · parent ${esc(x.parentDomain)}`:''}<br><strong>Identified as:</strong> ${esc(x.description||'Unknown service')}${x.inferredCategory?`<br><strong>Hostname inference:</strong> ${esc(x.inferredCategory)}`:''}<br><strong>${esc(x.source)}:</strong> ${esc(x.summary)}${cats?`<br><strong>All provider categories:</strong> ${esc(cats)}`:''}${x.virusTotal?`<br><strong>Security checks:</strong> ${a.malicious||0} malicious, ${a.suspicious||0} suspicious, ${a.harmless||0} harmless · reputation ${esc(x.reputation??0)}${x.registrar?' · registrar '+esc(x.registrar):''}`:`<br>${esc(x.virusTotalError||'')}`}${x.observed?`<br><strong>Latest public observation:</strong> ${esc(x.title||'No page title')} · IP ${esc(x.ip||'unknown')} · ${esc(x.country||'country unknown')}${x.server?' · '+esc(x.server):''}`:''}`}catch(x){out.textContent='Lookup failed: '+x.message}finally{explain.disabled=false}return}const b=e.target.closest('.ignoreEvidence');if(!b)return;b.disabled=true;const domain=b.dataset.domain.toLowerCase(),ignored=b.dataset.ignored==='true';try{await api('/api/ignored',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain,ignored})});model.events.forEach(x=>{if(x.domain.toLowerCase()===domain)x.ignored=ignored});render()}catch(x){alert(x.message);b.disabled=false}};
$('#saveAliases').onclick=async()=>{const aliases={},macAliases={};document.querySelectorAll('[data-ip]').forEach(i=>{const name=i.value.trim();if(!name)return;if(i.dataset.mac)macAliases[i.dataset.mac.toUpperCase()]=name;else aliases[i.dataset.ip]=name});await api('/api/aliases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({aliases,macAliases})});await load()};
$('#discoverNames').onclick=async()=>{$('#discoverNames').disabled=true;$('#discoveryStatus').textContent='Scanning reverse DNS, NetBIOS, and ARP (usually under one minute)…';try{await api('/api/discover',{method:'POST'});$('#discoveryStatus').textContent='Scan complete. Devices with NetBIOS disabled may show only an IP and MAC address.';await load()}catch(e){$('#discoveryStatus').textContent=e.message}finally{$('#discoverNames').disabled=false}};
$('#exportCsv').onclick=()=>{const x=filtered().sessions;csvDownload('HomeWatch-sessions.csv',[['Device','IP','Start','End','Observed seconds','Raw DNS requests','Logical contacts','Time to first media seconds','Media window seconds','Possible playback phases','Asset-loading bursts','Advertising requests','Possible navigation changes','Assessment','Confidence','Direct domains','Stream domains','Asset domains','Advertising domains','Narrative'],...x.map(s=>[s.clientName,s.client,s.start,s.end,s.durationSeconds,s.requests,s.logicalContacts,s.timeToFirstStreamSeconds,s.streamWindowSeconds,s.possiblePlaybackPhases,s.assetLoadingBursts,s.advertisingRequests,s.possibleNavigationChanges,s.assessment,s.confidence,(s.directDomains||[]).join(' | '),(s.streamDomains||[]).join(' | '),(s.assetDomains||[]).join(' | '),(s.advertisingDomains||[]).join(' | '),s.narrative])])};
$('#exportActivity').onclick=()=>{const x=filtered().events;csvDownload('HomeWatch-activity.csv',[['Time','Device','IP','Domain','DNS query type','DNS response types','DNS response values','Owner','Service category','Category confidence','Description','Result','Evidence','Evidence confidence'],...x.map(e=>[e.time,e.clientName,e.client,e.domain,e.queryType,(e.responseTypes||[]).join(' | '),(e.responseValues||[]).join(' | '),e.serviceOwner,e.serviceCategory,e.serviceCategoryConfidence,e.description,e.status,e.label,e.confidence])])};
$('#exportJson').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(filtered().events,null,2)],{type:'application/json'}));a.download='HomeWatch-activity.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
async function loadSettings(){const s=await api('/api/settings');$('#retentionDays').value=s.retentionDays;$('#categoryListUrl').value=s.categoryListUrl||'';$('#autoUpdateCategories').checked=!!s.autoUpdateCategories;$('#virusTotalApiKey').value='';$('#removeVirusTotalApiKey').checked=false;$('#virusTotalStatus').textContent=s.virusTotalConfigured?'VirusTotal API key is saved and encrypted.':'No VirusTotal API key saved.';$('#ntfyTopicUrl').value='';$('#removeNtfyTopicUrl').checked=false;$('#ntfyStatus').textContent=s.ntfyConfigured?'Phone notification topic is saved and encrypted.':'No phone notification topic saved.';$('#adguardLink').href=s.adGuardUrl||'http://127.0.0.1'}
async function saveSettings(updateNow){$('#settingsStatus').textContent='Saving…';try{await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({retentionDays:Number($('#retentionDays').value),categoryListUrl:$('#categoryListUrl').value.trim(),autoUpdateCategories:$('#autoUpdateCategories').checked,virusTotalApiKey:$('#virusTotalApiKey').value.trim(),removeVirusTotalApiKey:$('#removeVirusTotalApiKey').checked,ntfyTopicUrl:$('#ntfyTopicUrl').value.trim(),removeNtfyTopicUrl:$('#removeNtfyTopicUrl').checked,updateNow})});$('#settingsStatus').textContent=updateNow?'Settings saved and category list updated.':'Settings saved.';await loadSettings();return true}catch(e){$('#settingsStatus').textContent=e.message;return false}}
$('#settingsForm').onsubmit=e=>{e.preventDefault();saveSettings(false)};$('#updateCategories').onclick=()=>saveSettings(true);init();setInterval(()=>{if(!$('#dashboard').classList.contains('hidden'))load(true)},5000);
$('#testNotification').onclick=async()=>{if($('#ntfyTopicUrl').value.trim()&&!await saveSettings(false))return;$('#settingsStatus').textContent='Sending test notification…';try{await api('/api/notifications/test',{method:'POST'});$('#settingsStatus').textContent='Test notification sent. If it did not arrive, verify the phone subscription and notification permission.'}catch(e){$('#settingsStatus').textContent=e.message}};
